services:
  - type: web
    name: n8n-free
    plan: free
    buildCommand: |
      export NODE_OPTIONS="--max-old-space-size=1024"
      pnpm install --frozen-lockfile --ignore-scripts
      pnpm run build --filter=@n8n/core --filter=@n8n/workflow
    startCommand: |
      export NODE_OPTIONS="--max-old-space-size=1024"
      node packages/cli/bin/n8n
    envVars:
      - key: NODE_ENV
        value: production
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        generateValue: true
